[build]
builderPath = "./backend"

[phases.setup]
nixPkgs = ["maven", "jdk17"]

[phases.build]
cmds = [
  "cd backend",
  "chmod +x ./mvnw",
  "./mvnw -DoutputFile=target/mvn-dependency-list.log -B -DskipTests clean dependency:list install"
]

[start]
cmd = "cd backend && java -jar target/*.jar"