# 1st stage: Build with Maven
FROM maven:3.9.5-eclipse-temurin-21 AS build
WORKDIR /app
COPY backend/ .
RUN ./mvnw clean package -DskipTests

# 2nd stage: Run the app
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
